#+PROPERTY: LOGGING nil

* Ideas

** TODO Avoid refreshing section too often

On large repos, updating the section from scratch takes some time.  It would be good to avoid doing this too often in large repos.

*** TODO Option for when to refresh it

There should be an option for how often to refresh the to-dos section:

+  =always=
+  =manually=
+  a number of seconds (not automatically, but whenever the status buffer is refreshed and this many seconds have elapsed)

=memoize= can be used to implement this, probably with a proxy function to handle always/manually.

*** TODO Set option automatically in large repos

The parsing/insertion should be timed, and if it takes too long, the previous option should be automatically set to timeout or manual.
** TODO Restore timeout feature

Not strictly necessary anymore, but still good to have, and should be simple to do.

** TODO Ignore files/directories in scanners

*** TODO rg

Should probably use =--glob=:

#+BEGIN_EXAMPLE
    -g, --glob <GLOB>...                    
            Include or exclude files and directories for searching that match the given
            glob. This always overrides any other ignore logic. Multiple glob flags may be
            used. Globbing rules match .gitignore globs. Precede a glob with a ! to exclude
            it.

        --iglob <GLOB>...                   
            Include or exclude files and directories for searching that match the given
            glob. This always overrides any other ignore logic. Multiple glob flags may be
            used. Globbing rules match .gitignore globs. Precede a glob with a ! to exclude
            it. Globs are matched case insensitively.
#+END_EXAMPLE

*** TODO ag

*** TODO git-grep

*** TODO find-grep
